<?xml version="1.0" encoding="UTF-8"?>
<RECIPES>
  <RECIPE>
    <NAME>Prickly Pear Sour</NAME>
    <STYLE>
      <STYLE_GUIDE>BJCP</STYLE_GUIDE>
      <VERSION>1</VERSION>
      <NAME>Fruit Beer</NAME>
      <STYLE_LETTER>A</STYLE_LETTER>
      <CATEGORY_NUMBER>20</CATEGORY_NUMBER>
      <TYPE>Ale</TYPE>
      <OG_MIN>1.0</OG_MIN>
      <OG_MAX>1.15</OG_MAX>
      <FG_MIN>1.0</FG_MIN>
      <FG_MAX>1.15</FG_MAX>
      <IBU_MIN>0.0</IBU_MIN>
      <IBU_MAX>120.0</IBU_MAX>
      <COLOR_MIN>0.0</COLOR_MIN>
      <COLOR_MAX>40.0</COLOR_MAX>
      <ABV_MIN>1.0</ABV_MIN>
      <ABV_MAX>14.0</ABV_MAX>
    </STYLE>
    <FERMENTABLES>
      <FERMENTABLE>
        <NAME>Unmalted Wheat (BE)</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Adjunct</TYPE>
        <YIELD>77.7369898510041</YIELD>
        <AMOUNT>2.2679618500000003</AMOUNT>
        <DISPLAY_AMOUNT>5.0 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.036</POTENTIAL>
        <COLOR>2</COLOR>
        <DISPLAY_COLOR>2 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
      <FERMENTABLE>
        <NAME>2-Row (US)</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Base Malt</TYPE>
        <YIELD>79.89635068019865</YIELD>
        <AMOUNT>2.2679618500000003</AMOUNT>
        <DISPLAY_AMOUNT>5.0 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.037</POTENTIAL>
        <COLOR>1</COLOR>
        <DISPLAY_COLOR>1 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
      <FERMENTABLE>
        <NAME>Honey Malt (CA)</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Caramel/Crystal Malt</TYPE>
        <YIELD>79.89635068019865</YIELD>
        <AMOUNT>0.226796185</AMOUNT>
        <DISPLAY_AMOUNT>0.5 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.037</POTENTIAL>
        <COLOR>25</COLOR>
        <DISPLAY_COLOR>25 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
      <FERMENTABLE>
        <NAME>Victory (US)</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Kilned Malt</TYPE>
        <YIELD>73.41826819261497</YIELD>
        <AMOUNT>0.226796185</AMOUNT>
        <DISPLAY_AMOUNT>0.5 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.034</POTENTIAL>
        <COLOR>28</COLOR>
        <DISPLAY_COLOR>28 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
    </FERMENTABLES>
    <HOPS>
      <HOP>
        <NAME>Target (UK)</NAME>
        <ORIGIN>United Kingdom</ORIGIN>
        <ALPHA>11.0</ALPHA>
        <BETA></BETA>
        <AMOUNT>0.01417475</AMOUNT>
        <DISPLAY_AMOUNT>0.5 oz</DISPLAY_AMOUNT>
        <USE>Boil</USE>
        <FORM>Pellet</FORM>
        <TIME>5</TIME>
        <DISPLAY_TIME>5.0 min</DISPLAY_TIME>
        <NOTES></NOTES>
      </HOP>
    </HOPS>
    <YEASTS>
      <YEAST>
        <LABORATORY>Wyeast</LABORATORY>
        <NAME>California Lager</NAME>
        <TYPE>Lager</TYPE>
        <FORM>Liquid</FORM>
        <ATTENUATION>69.0</ATTENUATION>
      </YEAST>
    </YEASTS>
    <MISCS/>
    <TYPE>All Grain</TYPE>
    <BREWER>scottonthepot</BREWER>
    <BATCH_SIZE>20.81976479</BATCH_SIZE>
    <BOIL_SIZE>24.983717748</BOIL_SIZE>
    <BOIL_TIME>60</BOIL_TIME>
    <EFFICIENCY>75.0</EFFICIENCY>
  </RECIPE>
</RECIPES>
