<?xml version="1.0" encoding="UTF-8"?>
<RECIPES>
  <RECIPE>
    <NAME>Blonde Ale</NAME>
    <STYLE>
      <STYLE_GUIDE>BJCP</STYLE_GUIDE>
      <VERSION>1</VERSION>
      <NAME>Blonde Ale</NAME>
      <STYLE_LETTER>B</STYLE_LETTER>
      <CATEGORY_NUMBER>6</CATEGORY_NUMBER>
      <TYPE>Ale</TYPE>
      <OG_MIN>1.038</OG_MIN>
      <OG_MAX>1.054</OG_MAX>
      <FG_MIN>1.008</FG_MIN>
      <FG_MAX>1.013</FG_MAX>
      <IBU_MIN>15.0</IBU_MIN>
      <IBU_MAX>28.0</IBU_MAX>
      <COLOR_MIN>3.0</COLOR_MIN>
      <COLOR_MAX>6.0</COLOR_MAX>
      <ABV_MIN>3.8</ABV_MIN>
      <ABV_MAX>5.5</ABV_MAX>
    </STYLE>
    <FERMENTABLES>
      <FERMENTABLE>
        <NAME>2-Row (US)</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Base Malt</TYPE>
        <YIELD>79.89635068019865</YIELD>
        <AMOUNT>3.62873896</AMOUNT>
        <DISPLAY_AMOUNT>8.0 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.037</POTENTIAL>
        <COLOR>1</COLOR>
        <DISPLAY_COLOR>1 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
      <FERMENTABLE>
        <NAME>Honey Malt (CA)</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Caramel/Crystal Malt</TYPE>
        <YIELD>79.89635068019865</YIELD>
        <AMOUNT>0.226796185</AMOUNT>
        <DISPLAY_AMOUNT>0.5 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.037</POTENTIAL>
        <COLOR>25</COLOR>
        <DISPLAY_COLOR>25 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
    </FERMENTABLES>
    <HOPS>
      <HOP>
        <NAME>Saaz (CZ)</NAME>
        <ORIGIN>Czech Republic</ORIGIN>
        <ALPHA>3.25</ALPHA>
        <BETA></BETA>
        <AMOUNT>0.04252424999999999</AMOUNT>
        <DISPLAY_AMOUNT>1.5 oz</DISPLAY_AMOUNT>
        <USE>Boil</USE>
        <FORM>Pellet</FORM>
        <TIME>60</TIME>
        <DISPLAY_TIME>60.0 min</DISPLAY_TIME>
        <NOTES></NOTES>
      </HOP>
    </HOPS>
    <YEASTS>
      <YEAST>
        <LABORATORY>Fermentis</LABORATORY>
        <NAME>Safale US-05</NAME>
        <TYPE>Ale</TYPE>
        <FORM>Dry</FORM>
        <ATTENUATION>85.5</ATTENUATION>
      </YEAST>
    </YEASTS>
    <MISCS/>
    <TYPE>All Grain</TYPE>
    <BREWER>scottonthepot</BREWER>
    <BATCH_SIZE>20.81976479</BATCH_SIZE>
    <BOIL_SIZE>24.983717748</BOIL_SIZE>
    <BOIL_TIME>60</BOIL_TIME>
    <EFFICIENCY>80.0</EFFICIENCY>
  </RECIPE>
</RECIPES>
