<?xml version="1.0" encoding="UTF-8"?>
<RECIPES>
  <RECIPE>
    <NAME>Black Lager</NAME>
    <STYLE>
      <STYLE_GUIDE>BJCP</STYLE_GUIDE>
      <VERSION>1</VERSION>
      <NAME>Schwarzbier (Black Beer)</NAME>
      <STYLE_LETTER>C</STYLE_LETTER>
      <CATEGORY_NUMBER>4</CATEGORY_NUMBER>
      <TYPE>Lager</TYPE>
      <OG_MIN>1.046</OG_MIN>
      <OG_MAX>1.052</OG_MAX>
      <FG_MIN>1.01</FG_MIN>
      <FG_MAX>1.016</FG_MAX>
      <IBU_MIN>22.0</IBU_MIN>
      <IBU_MAX>32.0</IBU_MAX>
      <COLOR_MIN>17.0</COLOR_MIN>
      <COLOR_MAX>30.0</COLOR_MAX>
      <ABV_MIN>4.4</ABV_MIN>
      <ABV_MAX>5.4</ABV_MAX>
    </STYLE>
    <FERMENTABLES>
      <FERMENTABLE>
        <NAME>Maris Otter Pale (UK)</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Base Malt</TYPE>
        <YIELD>82.05571150939322</YIELD>
        <AMOUNT>2.2679618500000003</AMOUNT>
        <DISPLAY_AMOUNT>5.0 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.038</POTENTIAL>
        <COLOR>3</COLOR>
        <DISPLAY_COLOR>3 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
      <FERMENTABLE>
        <NAME>Munich (BE)</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Kilned Malt</TYPE>
        <YIELD>82.05571150939322</YIELD>
        <AMOUNT>2.2679618500000003</AMOUNT>
        <DISPLAY_AMOUNT>5.0 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.038</POTENTIAL>
        <COLOR>6</COLOR>
        <DISPLAY_COLOR>6 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
      <FERMENTABLE>
        <NAME>Smoked Malt (US)</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Adjunct</TYPE>
        <YIELD>79.89635068019865</YIELD>
        <AMOUNT>0.45359237</AMOUNT>
        <DISPLAY_AMOUNT>1.0 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.037</POTENTIAL>
        <COLOR>5</COLOR>
        <DISPLAY_COLOR>5 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
      <FERMENTABLE>
        <NAME>Midnight Wheat Malt (US)</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Adjunct</TYPE>
        <YIELD>71.25890736342042</YIELD>
        <AMOUNT>0.226796185</AMOUNT>
        <DISPLAY_AMOUNT>0.5 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.033</POTENTIAL>
        <COLOR>550</COLOR>
        <DISPLAY_COLOR>550 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
      <FERMENTABLE>
        <NAME>Honey Malt (CA)</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Caramel/Crystal Malt</TYPE>
        <YIELD>79.89635068019865</YIELD>
        <AMOUNT>0.226796185</AMOUNT>
        <DISPLAY_AMOUNT>0.5 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.037</POTENTIAL>
        <COLOR>25</COLOR>
        <DISPLAY_COLOR>25 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
    </FERMENTABLES>
    <HOPS>
      <HOP>
        <NAME>Northern Brewer (US)</NAME>
        <ORIGIN>United States</ORIGIN>
        <ALPHA>9.0</ALPHA>
        <BETA></BETA>
        <AMOUNT>0.056699</AMOUNT>
        <DISPLAY_AMOUNT>2.0 oz</DISPLAY_AMOUNT>
        <USE>Boil</USE>
        <FORM>Pellet</FORM>
        <TIME>10</TIME>
        <DISPLAY_TIME>10.0 min</DISPLAY_TIME>
        <NOTES></NOTES>
      </HOP>
    </HOPS>
    <YEASTS>
      <YEAST>
        <LABORATORY>Wyeast</LABORATORY>
        <NAME>California Lager</NAME>
        <TYPE>Lager</TYPE>
        <FORM>Liquid</FORM>
        <ATTENUATION>69.0</ATTENUATION>
      </YEAST>
    </YEASTS>
    <MISCS/>
    <TYPE>All Grain</TYPE>
    <BREWER>scottonthepot</BREWER>
    <BATCH_SIZE>20.81976479</BATCH_SIZE>
    <BOIL_SIZE>26.876423638</BOIL_SIZE>
    <BOIL_TIME>60</BOIL_TIME>
    <EFFICIENCY>75.0</EFFICIENCY>
  </RECIPE>
</RECIPES>
