<?xml version="1.0" encoding="UTF-8"?>
<RECIPES>
  <RECIPE>
    <NAME>Peanut Butter Jelly Time</NAME>
    <STYLE>
      <STYLE_GUIDE>BJCP</STYLE_GUIDE>
      <VERSION>1</VERSION>
      <NAME>Fruit Beer</NAME>
      <STYLE_LETTER>A</STYLE_LETTER>
      <CATEGORY_NUMBER>20</CATEGORY_NUMBER>
      <TYPE>Ale</TYPE>
      <OG_MIN>1.0</OG_MIN>
      <OG_MAX>1.15</OG_MAX>
      <FG_MIN>1.0</FG_MIN>
      <FG_MAX>1.15</FG_MAX>
      <IBU_MIN>0.0</IBU_MIN>
      <IBU_MAX>120.0</IBU_MAX>
      <COLOR_MIN>0.0</COLOR_MIN>
      <COLOR_MAX>40.0</COLOR_MAX>
      <ABV_MIN>1.0</ABV_MIN>
      <ABV_MAX>14.0</ABV_MAX>
    </STYLE>
    <FERMENTABLES>
      <FERMENTABLE>
        <NAME>Maris Otter Pale (UK)</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Base Malt</TYPE>
        <YIELD>82.05571150939322</YIELD>
        <AMOUNT>4.1957294225</AMOUNT>
        <DISPLAY_AMOUNT>9.25 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.038</POTENTIAL>
        <COLOR>3</COLOR>
        <DISPLAY_COLOR>3 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
      <FERMENTABLE>
        <NAME>Rye (US)</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Adjunct</TYPE>
        <YIELD>82.05571150939322</YIELD>
        <AMOUNT>1.1339809250000001</AMOUNT>
        <DISPLAY_AMOUNT>2.5 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.038</POTENTIAL>
        <COLOR>3</COLOR>
        <DISPLAY_COLOR>3 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
      <FERMENTABLE>
        <NAME>Caramel/Crystal 60L (US)</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Caramel/Crystal Malt</TYPE>
        <YIELD>73.41826819261497</YIELD>
        <AMOUNT>0.226796185</AMOUNT>
        <DISPLAY_AMOUNT>0.5 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.034</POTENTIAL>
        <COLOR>60</COLOR>
        <DISPLAY_COLOR>60 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
      <FERMENTABLE>
        <NAME>Aromatic Malt (US)</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Kilned Malt</TYPE>
        <YIELD>75.57762902180954</YIELD>
        <AMOUNT>0.1133980925</AMOUNT>
        <DISPLAY_AMOUNT>0.25 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.035</POTENTIAL>
        <COLOR>20</COLOR>
        <DISPLAY_COLOR>20 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
    </FERMENTABLES>
    <HOPS>
      <HOP>
        <NAME>Belma</NAME>
        <ORIGIN nil="true"/>
        <ALPHA>11.3</ALPHA>
        <BETA></BETA>
        <AMOUNT>0.021262124999999996</AMOUNT>
        <DISPLAY_AMOUNT>0.75 oz</DISPLAY_AMOUNT>
        <USE>Boil</USE>
        <FORM>Pellet</FORM>
        <TIME>60</TIME>
        <DISPLAY_TIME>60.0 min</DISPLAY_TIME>
        <NOTES></NOTES>
      </HOP>
    </HOPS>
    <YEASTS>
      <YEAST>
        <LABORATORY>Wyeast</LABORATORY>
        <NAME>British Ale</NAME>
        <TYPE>Ale</TYPE>
        <FORM>Liquid</FORM>
        <ATTENUATION>74.0</ATTENUATION>
      </YEAST>
    </YEASTS>
    <MISCS>
      <MISC>
        <NAME>Strawberries (Frozen)</NAME>
        <USE>Secondary</USE>
        <TIME>1.0</TIME>
        <AMOUNT>16.0</AMOUNT>
        <AMOUNT_IS_WEIGHT>false</AMOUNT_IS_WEIGHT>
        <NOTES></NOTES>
        <DISPLAY_AMOUNT>16.0 </DISPLAY_AMOUNT>
        <DISPLAY_TIME>1.0 </DISPLAY_TIME>
      </MISC>
      <MISC>
        <NAME>PB2</NAME>
        <USE>Secondary</USE>
        <TIME>1.0</TIME>
        <AMOUNT>16.0</AMOUNT>
        <AMOUNT_IS_WEIGHT>false</AMOUNT_IS_WEIGHT>
        <NOTES nil="true"/>
        <DISPLAY_AMOUNT>16.0 </DISPLAY_AMOUNT>
        <DISPLAY_TIME>1.0 </DISPLAY_TIME>
      </MISC>
    </MISCS>
    <TYPE>All Grain</TYPE>
    <BREWER>scottonthepot</BREWER>
    <BATCH_SIZE>22.71247068</BATCH_SIZE>
    <BOIL_SIZE>27.254964816</BOIL_SIZE>
    <BOIL_TIME>60</BOIL_TIME>
    <EFFICIENCY>75.0</EFFICIENCY>
  </RECIPE>
</RECIPES>
