<?xml version="1.0" encoding="UTF-8"?>
<RECIPES>
  <RECIPE>
    <NAME>The Mondays</NAME>
    <STYLE>
      <STYLE_GUIDE>BJCP</STYLE_GUIDE>
      <VERSION>1</VERSION>
      <NAME>Brown Porter</NAME>
      <STYLE_LETTER>A</STYLE_LETTER>
      <CATEGORY_NUMBER>12</CATEGORY_NUMBER>
      <TYPE>Ale</TYPE>
      <OG_MIN>1.04</OG_MIN>
      <OG_MAX>1.052</OG_MAX>
      <FG_MIN>1.008</FG_MIN>
      <FG_MAX>1.014</FG_MAX>
      <IBU_MIN>18.0</IBU_MIN>
      <IBU_MAX>35.0</IBU_MAX>
      <COLOR_MIN>20.0</COLOR_MIN>
      <COLOR_MAX>30.0</COLOR_MAX>
      <ABV_MIN>4.0</ABV_MIN>
      <ABV_MAX>5.4</ABV_MAX>
    </STYLE>
    <FERMENTABLES>
      <FERMENTABLE>
        <NAME>Maris Otter Pale Ale Malt</NAME>
        <ORIGIN>United Kingdom</ORIGIN>
        <TYPE>Base Malt</TYPE>
        <YIELD>77.7369898510041</YIELD>
        <AMOUNT>4.082331330000001</AMOUNT>
        <DISPLAY_AMOUNT>9.0 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.036</POTENTIAL>
        <COLOR>2</COLOR>
        <DISPLAY_COLOR>2 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
      <FERMENTABLE>
        <NAME>Dark Munich Malt</NAME>
        <ORIGIN>Germany</ORIGIN>
        <TYPE>Grain</TYPE>
        <YIELD>79.89635068019865</YIELD>
        <AMOUNT>1.587573295</AMOUNT>
        <DISPLAY_AMOUNT>3.5 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.037</POTENTIAL>
        <COLOR>12</COLOR>
        <DISPLAY_COLOR>12 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
      <FERMENTABLE>
        <NAME>Honey</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Sugar</TYPE>
        <YIELD>75.57762902180954</YIELD>
        <AMOUNT>0.90718474</AMOUNT>
        <DISPLAY_AMOUNT>2.0 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.035</POTENTIAL>
        <COLOR>1</COLOR>
        <DISPLAY_COLOR>1 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
      <FERMENTABLE>
        <NAME>Honey Malt</NAME>
        <ORIGIN>Canada</ORIGIN>
        <TYPE>Caramel/Crystal Malt</TYPE>
        <YIELD>79.89635068019865</YIELD>
        <AMOUNT>0.45359237</AMOUNT>
        <DISPLAY_AMOUNT>1.0 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.037</POTENTIAL>
        <COLOR>23</COLOR>
        <DISPLAY_COLOR>23 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
      <FERMENTABLE>
        <NAME>Pale Chocolate Malt</NAME>
        <ORIGIN>United Kingdom</ORIGIN>
        <TYPE>Roasted Malt</TYPE>
        <YIELD>69.09954653422587</YIELD>
        <AMOUNT>0.226796185</AMOUNT>
        <DISPLAY_AMOUNT>0.5 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.032</POTENTIAL>
        <COLOR>197</COLOR>
        <DISPLAY_COLOR>197 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
      <FERMENTABLE>
        <NAME>Belgian Special B</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Caramel/Crystal Malt</TYPE>
        <YIELD>64.78082487583676</YIELD>
        <AMOUNT>0.226796185</AMOUNT>
        <DISPLAY_AMOUNT>0.5 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.03</POTENTIAL>
        <COLOR>220</COLOR>
        <DISPLAY_COLOR>220 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
    </FERMENTABLES>
    <HOPS>
      <HOP>
        <NAME>Belma</NAME>
        <ORIGIN></ORIGIN>
        <ALPHA>10.4</ALPHA>
        <BETA></BETA>
        <AMOUNT>0.0283495</AMOUNT>
        <DISPLAY_AMOUNT>1.0 oz</DISPLAY_AMOUNT>
        <USE>Boil</USE>
        <FORM>Pellet</FORM>
        <TIME>60</TIME>
        <DISPLAY_TIME>60.0 min</DISPLAY_TIME>
        <NOTES></NOTES>
      </HOP>
    </HOPS>
    <YEASTS>
      <YEAST>
        <LABORATORY>Wyeast</LABORATORY>
        <NAME>London Ale</NAME>
        <TYPE>Ale</TYPE>
        <FORM>Liquid</FORM>
        <ATTENUATION>75.0</ATTENUATION>
      </YEAST>
    </YEASTS>
    <MISCS>
      <MISC>
        <NAME>Roasted Pecans</NAME>
        <USE>Mash</USE>
        <TIME>60.0</TIME>
        <AMOUNT>2.0</AMOUNT>
        <AMOUNT_IS_WEIGHT>false</AMOUNT_IS_WEIGHT>
        <NOTES></NOTES>
        <DISPLAY_AMOUNT>2.0 </DISPLAY_AMOUNT>
        <DISPLAY_TIME>60.0 </DISPLAY_TIME>
      </MISC>
    </MISCS>
    <TYPE>All Grain</TYPE>
    <BREWER>scottonthepot</BREWER>
    <BATCH_SIZE>20.81976479</BATCH_SIZE>
    <BOIL_SIZE>26.0436330464</BOIL_SIZE>
    <BOIL_TIME>60</BOIL_TIME>
    <EFFICIENCY>75.0</EFFICIENCY>
  </RECIPE>
</RECIPES>
