<?xml version="1.0" encoding="UTF-8"?>
<RECIPES>
  <RECIPE>
    <NAME>Vanilla Porter</NAME>
    <STYLE>
      <STYLE_GUIDE>BJCP</STYLE_GUIDE>
      <VERSION>1</VERSION>
      <NAME>Robust Porter</NAME>
      <STYLE_LETTER>B</STYLE_LETTER>
      <CATEGORY_NUMBER>12</CATEGORY_NUMBER>
      <TYPE>Ale</TYPE>
      <OG_MIN>1.048</OG_MIN>
      <OG_MAX>1.065</OG_MAX>
      <FG_MIN>1.012</FG_MIN>
      <FG_MAX>1.016</FG_MAX>
      <IBU_MIN>25.0</IBU_MIN>
      <IBU_MAX>50.0</IBU_MAX>
      <COLOR_MIN>22.0</COLOR_MIN>
      <COLOR_MAX>35.0</COLOR_MAX>
      <ABV_MIN>4.8</ABV_MIN>
      <ABV_MAX>6.5</ABV_MAX>
    </STYLE>
    <FERMENTABLES>
      <FERMENTABLE>
        <NAME>Maris Otter Pale (UK)</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Base Malt</TYPE>
        <YIELD>82.05571150939322</YIELD>
        <AMOUNT>3.855535145</AMOUNT>
        <DISPLAY_AMOUNT>8.5 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.038</POTENTIAL>
        <COLOR>3</COLOR>
        <DISPLAY_COLOR>3 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
      <FERMENTABLE>
        <NAME>Munich - 60L (US)</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Kilned Malt</TYPE>
        <YIELD>71.25890736342042</YIELD>
        <AMOUNT>0.90718474</AMOUNT>
        <DISPLAY_AMOUNT>2.0 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.033</POTENTIAL>
        <COLOR>60</COLOR>
        <DISPLAY_COLOR>60 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
      <FERMENTABLE>
        <NAME>Pale Chocolate (UK)</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Roasted Malt</TYPE>
        <YIELD>71.25890736342042</YIELD>
        <AMOUNT>0.226796185</AMOUNT>
        <DISPLAY_AMOUNT>0.5 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.033</POTENTIAL>
        <COLOR>207</COLOR>
        <DISPLAY_COLOR>207 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
      <FERMENTABLE>
        <NAME>Wheat (US)</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Adjunct</TYPE>
        <YIELD>82.05571150939322</YIELD>
        <AMOUNT>0.226796185</AMOUNT>
        <DISPLAY_AMOUNT>0.5 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.038</POTENTIAL>
        <COLOR>1</COLOR>
        <DISPLAY_COLOR>1 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
      <FERMENTABLE>
        <NAME>Caramel/Crystal 60L (US)</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Caramel/Crystal Malt</TYPE>
        <YIELD>73.41826819261497</YIELD>
        <AMOUNT>0.226796185</AMOUNT>
        <DISPLAY_AMOUNT>0.5 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.034</POTENTIAL>
        <COLOR>60</COLOR>
        <DISPLAY_COLOR>60 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
      <FERMENTABLE>
        <NAME>Aromatic Malt (US)</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Kilned Malt</TYPE>
        <YIELD>75.57762902180954</YIELD>
        <AMOUNT>0.226796185</AMOUNT>
        <DISPLAY_AMOUNT>0.5 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.035</POTENTIAL>
        <COLOR>20</COLOR>
        <DISPLAY_COLOR>20 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
    </FERMENTABLES>
    <HOPS>
      <HOP>
        <NAME>Belma</NAME>
        <ORIGIN nil="true"/>
        <ALPHA>11.0</ALPHA>
        <BETA></BETA>
        <AMOUNT>0.0283495</AMOUNT>
        <DISPLAY_AMOUNT>1.0 oz</DISPLAY_AMOUNT>
        <USE>First Wort</USE>
        <FORM>Pellet</FORM>
        <TIME>60</TIME>
        <DISPLAY_TIME>60.0 min</DISPLAY_TIME>
        <NOTES></NOTES>
      </HOP>
    </HOPS>
    <YEASTS>
      <YEAST>
        <LABORATORY>White Labs</LABORATORY>
        <NAME>British Ale Yeast</NAME>
        <TYPE>Ale</TYPE>
        <FORM>Liquid</FORM>
        <ATTENUATION>70.5</ATTENUATION>
      </YEAST>
    </YEASTS>
    <MISCS>
      <MISC>
        <NAME>Vanilla Beans</NAME>
        <USE>Boil</USE>
        <TIME>1.0</TIME>
        <AMOUNT>1.0</AMOUNT>
        <AMOUNT_IS_WEIGHT>false</AMOUNT_IS_WEIGHT>
        <NOTES></NOTES>
        <DISPLAY_AMOUNT>1.0 </DISPLAY_AMOUNT>
        <DISPLAY_TIME>1.0 </DISPLAY_TIME>
      </MISC>
      <MISC>
        <NAME>Vanilla Extract</NAME>
        <USE>Keg</USE>
        <TIME>1.0</TIME>
        <AMOUNT>1.0</AMOUNT>
        <AMOUNT_IS_WEIGHT>false</AMOUNT_IS_WEIGHT>
        <NOTES></NOTES>
        <DISPLAY_AMOUNT>1.0 </DISPLAY_AMOUNT>
        <DISPLAY_TIME>1.0 </DISPLAY_TIME>
      </MISC>
    </MISCS>
    <TYPE>All Grain</TYPE>
    <BREWER>scottonthepot</BREWER>
    <BATCH_SIZE>20.81976479</BATCH_SIZE>
    <BOIL_SIZE>26.876423638</BOIL_SIZE>
    <BOIL_TIME>60</BOIL_TIME>
    <EFFICIENCY>75.0</EFFICIENCY>
  </RECIPE>
</RECIPES>
