<?xml version="1.0" encoding="UTF-8"?>
<RECIPES>
  <RECIPE>
    <NAME>Duck Duck Gose</NAME>
    <STYLE>
      <STYLE_GUIDE>BJCP</STYLE_GUIDE>
      <VERSION>1</VERSION>
      <NAME>Fruit Beer</NAME>
      <STYLE_LETTER>A</STYLE_LETTER>
      <CATEGORY_NUMBER>20</CATEGORY_NUMBER>
      <TYPE>Ale</TYPE>
      <OG_MIN>1.0</OG_MIN>
      <OG_MAX>1.15</OG_MAX>
      <FG_MIN>1.0</FG_MIN>
      <FG_MAX>1.15</FG_MAX>
      <IBU_MIN>0.0</IBU_MIN>
      <IBU_MAX>120.0</IBU_MAX>
      <COLOR_MIN>0.0</COLOR_MIN>
      <COLOR_MAX>40.0</COLOR_MAX>
      <ABV_MIN>1.0</ABV_MIN>
      <ABV_MAX>14.0</ABV_MAX>
    </STYLE>
    <FERMENTABLES>
      <FERMENTABLE>
        <NAME>White Wheat  (US)</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Adjunct</TYPE>
        <YIELD>86.37443316778233</YIELD>
        <AMOUNT>2.2679618500000003</AMOUNT>
        <DISPLAY_AMOUNT>5.0 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.04</POTENTIAL>
        <COLOR>2</COLOR>
        <DISPLAY_COLOR>2 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
      <FERMENTABLE>
        <NAME>2-Row (US)</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Base Malt</TYPE>
        <YIELD>79.89635068019865</YIELD>
        <AMOUNT>1.4741752025000001</AMOUNT>
        <DISPLAY_AMOUNT>3.25 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.037</POTENTIAL>
        <COLOR>1</COLOR>
        <DISPLAY_COLOR>1 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
      <FERMENTABLE>
        <NAME>Acidulated Malt (DE)</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Adjunct</TYPE>
        <YIELD>58.30274238825307</YIELD>
        <AMOUNT>0.90718474</AMOUNT>
        <DISPLAY_AMOUNT>2.0 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.027</POTENTIAL>
        <COLOR>3</COLOR>
        <DISPLAY_COLOR>3 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
      <FERMENTABLE>
        <NAME>Vienna (US)</NAME>
        <ORIGIN></ORIGIN>
        <TYPE>Kilned Malt</TYPE>
        <YIELD>75.57762902180954</YIELD>
        <AMOUNT>0.90718474</AMOUNT>
        <DISPLAY_AMOUNT>2.0 lb</DISPLAY_AMOUNT>
        <POTENTIAL>1.035</POTENTIAL>
        <COLOR>4</COLOR>
        <DISPLAY_COLOR>4 SRM</DISPLAY_COLOR>
        <ADD_AFTER_BOIL></ADD_AFTER_BOIL>
        <COARSE_FINE_DIFF></COARSE_FINE_DIFF>
        <MOISTURE></MOISTURE>
        <DIASTATIC_POWER></DIASTATIC_POWER>
        <PROTEIN></PROTEIN>
        <MAX_IN_BATCH></MAX_IN_BATCH>
        <RECOMMEND_MASH></RECOMMEND_MASH>
        <IBU_GAL_PER_LB></IBU_GAL_PER_LB>
        <NOTES></NOTES>
      </FERMENTABLE>
    </FERMENTABLES>
    <HOPS>
      <HOP>
        <NAME>Saaz (CZ)</NAME>
        <ORIGIN>Czech Republic</ORIGIN>
        <ALPHA>3.25</ALPHA>
        <BETA></BETA>
        <AMOUNT>0.0283495</AMOUNT>
        <DISPLAY_AMOUNT>1.0 oz</DISPLAY_AMOUNT>
        <USE>First Wort</USE>
        <FORM>Pellet</FORM>
        <TIME>60</TIME>
        <DISPLAY_TIME>60.0 min</DISPLAY_TIME>
        <NOTES></NOTES>
      </HOP>
    </HOPS>
    <YEASTS>
      <YEAST>
        <LABORATORY>Fermentis</LABORATORY>
        <NAME>Safale S-04</NAME>
        <TYPE>Ale</TYPE>
        <FORM>Dry</FORM>
        <ATTENUATION>70.0</ATTENUATION>
      </YEAST>
    </YEASTS>
    <MISCS>
      <MISC>
        <NAME>Sea Salt</NAME>
        <USE>Boil</USE>
        <TIME>15.0</TIME>
        <AMOUNT>0.75</AMOUNT>
        <AMOUNT_IS_WEIGHT>false</AMOUNT_IS_WEIGHT>
        <NOTES nil="true"/>
        <DISPLAY_AMOUNT>0.75 </DISPLAY_AMOUNT>
        <DISPLAY_TIME>15.0 </DISPLAY_TIME>
      </MISC>
      <MISC>
        <NAME>Orange Juice</NAME>
        <USE>Primary</USE>
        <TIME>5.0</TIME>
        <AMOUNT>0.5</AMOUNT>
        <AMOUNT_IS_WEIGHT>false</AMOUNT_IS_WEIGHT>
        <NOTES></NOTES>
        <DISPLAY_AMOUNT>0.5 </DISPLAY_AMOUNT>
        <DISPLAY_TIME>5.0 </DISPLAY_TIME>
      </MISC>
      <MISC>
        <NAME>Grains of Paradise</NAME>
        <USE>Boil</USE>
        <TIME>15.0</TIME>
        <AMOUNT>0.75</AMOUNT>
        <AMOUNT_IS_WEIGHT>false</AMOUNT_IS_WEIGHT>
        <NOTES></NOTES>
        <DISPLAY_AMOUNT>0.75 </DISPLAY_AMOUNT>
        <DISPLAY_TIME>15.0 </DISPLAY_TIME>
      </MISC>
    </MISCS>
    <TYPE>All Grain</TYPE>
    <BREWER>scottonthepot</BREWER>
    <BATCH_SIZE>20.81976479</BATCH_SIZE>
    <BOIL_SIZE>26.876423638</BOIL_SIZE>
    <BOIL_TIME>60</BOIL_TIME>
    <EFFICIENCY>75.0</EFFICIENCY>
  </RECIPE>
</RECIPES>
